
{% set data = load_setup_py_data() %}

package:
  name: learn_sphinx_doc
  version: {{ data["version"] }}

source:
  path: .

requirements:
  build:
    - python
    - setuptools
    # - jupyterlab>=1.0.0
  run:
    - python
    # - jupyterlab>=1.0.0
